os:
  - Visual Studio 2017
  - Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - hg summary
  - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake
  - cd ign-cmake
  - hg up default
  - md build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake ..
    -DCMAKE_CXX_FLAGS="-WX"
  # this will fail
  - cd ..
  - md build_
  - cd build_
  - cmake ..
    -DCMAKE_CXX_FLAGS="-WX"
    -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
